Repository wallentx/gh-sandbox, pull requests merged in 2022-11, with the labels that each got.

#6 make test.sh executable
  test.sh
Labels: modified

#7 Restructure repo
  app/test.sh
Labels: modified

#9 Fixing Profanity on readme
  README.md
Labels: fixed

#10 Letting people know I use Arch BTW in README.md
  .github/workflows/require-labels.yml
  README.md
Labels: modified

#11 Fixing format and name of labels workflow
  .github/workflows/require-labels.yml
Labels: fixed

#12 Scoping labels CI permissions
  .github/workflows/require-labels.yml
Labels: modified

#13 Switching to personal fork of labels CI
  .github/workflows/require-labels.yml
Labels: modified

#14 Release label test
  .github/release.yml
Labels: modified, :robot: CI

#15 This is my PR title
  testfile
Labels: added

#16 Welcome to meh swamp!
  CONTRIBUTING.md
Labels: documentation, added

#18 Made changes to test.sh that are totally not malicious
  app/test.sh
Labels: changed, :robot: CI, :slot_machine: Tests

#19 Rewrote everything in Bash resulting in a 4000% performance increase
  README.md
Labels: fixed
